const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
const REGISTER_FAILED = 'REGISTER_FAILED';
const LOGIN_FAILED = 'LOGIN_FAILED';
const LOGOUT = 'LOGOUT'
const USER_LOADED = 'USER_LOADED'


export {
    REGISTER_SUCCESS,
    LOGIN_SUCCESS,
    REGISTER_FAILED,
    LOGIN_FAILED,
    LOGOUT,
    USER_LOADED
}